
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Set mode and theme
POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

# Change defaults
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_SHOW_CHANGESET=true

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""

# Custom command to get pylint logs without re-running
# alias pylog="if [[ -e ".temp.pylint" ]] then; cat .temp.pylint; fi"

 # Colors
 POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
 POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
 POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
 POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
 POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="blue"
 POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
 POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
 POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="black"
 POWERLEVEL9K_VCS_CLEAN_FOREGROUND="yellow"
 POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
 POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
 POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
 POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
 POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"
 POWERLEVEL9K_PYENV_FOREGROUND="blue"
 POWERLEVEL9K_PYENV_BACKGROUND="black"
 POWERLEVEL9K_STATUS_FOREGROUND="red"
 POWERLEVEL9K_STATUS_BACKGROUND="black"
 POWERLEVEL9K_CUSTOM_PYLINT_BACKGROUND="black"
 POWERLEVEL9K_CUSTOM_PYLINT_FOREGROUND="red"

 # Prompts
 POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'context' 'dir' 'vcs' 'dir_writable' 'newline' 'os_icon_joined')
 POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status')

 plugins=(
          git
          zsh-syntax-highlighting
         )

source $ZSH/oh-my-zsh.sh


